"""replace work_type str with work_type_id fk in workforce models

Revision ID: 2ce23d10e027
Revises: 90bb2dc0849e
Create Date: 2026-04-29 11:54:29.030994

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "2ce23d10e027"
down_revision: Union[str, None] = "90bb2dc0849e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("wf_article_mapping", sa.Column("work_type_id", sa.UUID(), nullable=False))
    op.create_index(op.f("ix_wf_article_mapping_work_type_id"), "wf_article_mapping", ["work_type_id"], unique=False)
    op.create_foreign_key(
        "fk_wf_article_mapping_work_type_id", "wf_article_mapping", "work_types", ["work_type_id"], ["id"]
    )
    op.drop_column("wf_article_mapping", "work_type")
    op.add_column("wf_budget_items", sa.Column("work_type_id", sa.UUID(), nullable=False))
    op.create_index(op.f("ix_wf_budget_items_work_type_id"), "wf_budget_items", ["work_type_id"], unique=False)
    op.create_foreign_key("fk_wf_budget_items_work_type_id", "wf_budget_items", "work_types", ["work_type_id"], ["id"])
    op.drop_column("wf_budget_items", "work_type")
    op.add_column("wf_challenge_items", sa.Column("work_type_id", sa.UUID(), nullable=False))
    op.create_index(op.f("ix_wf_challenge_items_work_type_id"), "wf_challenge_items", ["work_type_id"], unique=False)
    op.create_foreign_key(
        "fk_wf_challenge_items_work_type_id", "wf_challenge_items", "work_types", ["work_type_id"], ["id"]
    )
    op.drop_column("wf_challenge_items", "work_type")
    op.add_column("wf_contractor_assignments", sa.Column("work_type_id", sa.UUID(), nullable=False))
    op.create_index(
        op.f("ix_wf_contractor_assignments_work_type_id"), "wf_contractor_assignments", ["work_type_id"], unique=False
    )
    op.create_foreign_key(
        "fk_wf_contractor_assignments_work_type_id", "wf_contractor_assignments", "work_types", ["work_type_id"], ["id"]
    )
    op.drop_column("wf_contractor_assignments", "work_type")
    op.add_column("wf_headcount_facts", sa.Column("work_type_id", sa.UUID(), nullable=False))
    op.create_index(op.f("ix_wf_headcount_facts_work_type_id"), "wf_headcount_facts", ["work_type_id"], unique=False)
    op.create_foreign_key(
        "fk_wf_headcount_facts_work_type_id", "wf_headcount_facts", "work_types", ["work_type_id"], ["id"]
    )
    op.drop_column("wf_headcount_facts", "work_type")
    op.add_column("wf_headcount_plans", sa.Column("work_type_id", sa.UUID(), nullable=False))
    op.create_index(op.f("ix_wf_headcount_plans_work_type_id"), "wf_headcount_plans", ["work_type_id"], unique=False)
    op.create_foreign_key(
        "fk_wf_headcount_plans_work_type_id", "wf_headcount_plans", "work_types", ["work_type_id"], ["id"]
    )
    op.drop_column("wf_headcount_plans", "work_type")
    op.add_column("wf_norms", sa.Column("work_type_id", sa.UUID(), nullable=False))
    op.create_index(op.f("ix_wf_norms_work_type_id"), "wf_norms", ["work_type_id"], unique=False)
    op.create_foreign_key("fk_wf_norms_work_type_id", "wf_norms", "work_types", ["work_type_id"], ["id"])
    op.drop_column("wf_norms", "work_type")
    op.add_column("wf_violations", sa.Column("work_type_id", sa.UUID(), nullable=False))
    op.create_index(op.f("ix_wf_violations_work_type_id"), "wf_violations", ["work_type_id"], unique=False)
    op.create_foreign_key("fk_wf_violations_work_type_id", "wf_violations", "work_types", ["work_type_id"], ["id"])
    op.drop_column("wf_violations", "work_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("wf_violations", sa.Column("work_type", sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint("fk_wf_violations_work_type_id", "wf_violations", type_="foreignkey")
    op.drop_index(op.f("ix_wf_violations_work_type_id"), table_name="wf_violations")
    op.drop_column("wf_violations", "work_type_id")
    op.add_column("wf_norms", sa.Column("work_type", sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint("fk_wf_norms_work_type_id", "wf_norms", type_="foreignkey")
    op.drop_index(op.f("ix_wf_norms_work_type_id"), table_name="wf_norms")
    op.drop_column("wf_norms", "work_type_id")
    op.add_column(
        "wf_headcount_plans", sa.Column("work_type", sa.VARCHAR(length=255), autoincrement=False, nullable=False)
    )
    op.drop_constraint("fk_wf_headcount_plans_work_type_id", "wf_headcount_plans", type_="foreignkey")
    op.drop_index(op.f("ix_wf_headcount_plans_work_type_id"), table_name="wf_headcount_plans")
    op.drop_column("wf_headcount_plans", "work_type_id")
    op.add_column(
        "wf_headcount_facts", sa.Column("work_type", sa.VARCHAR(length=255), autoincrement=False, nullable=False)
    )
    op.drop_constraint("fk_wf_headcount_facts_work_type_id", "wf_headcount_facts", type_="foreignkey")
    op.drop_index(op.f("ix_wf_headcount_facts_work_type_id"), table_name="wf_headcount_facts")
    op.drop_column("wf_headcount_facts", "work_type_id")
    op.add_column(
        "wf_contractor_assignments", sa.Column("work_type", sa.VARCHAR(length=255), autoincrement=False, nullable=False)
    )
    op.drop_constraint("fk_wf_contractor_assignments_work_type_id", "wf_contractor_assignments", type_="foreignkey")
    op.drop_index(op.f("ix_wf_contractor_assignments_work_type_id"), table_name="wf_contractor_assignments")
    op.drop_column("wf_contractor_assignments", "work_type_id")
    op.add_column(
        "wf_challenge_items", sa.Column("work_type", sa.VARCHAR(length=255), autoincrement=False, nullable=False)
    )
    op.drop_constraint("fk_wf_challenge_items_work_type_id", "wf_challenge_items", type_="foreignkey")
    op.drop_index(op.f("ix_wf_challenge_items_work_type_id"), table_name="wf_challenge_items")
    op.drop_column("wf_challenge_items", "work_type_id")
    op.add_column(
        "wf_budget_items", sa.Column("work_type", sa.VARCHAR(length=255), autoincrement=False, nullable=False)
    )
    op.drop_constraint("fk_wf_budget_items_work_type_id", "wf_budget_items", type_="foreignkey")
    op.drop_index(op.f("ix_wf_budget_items_work_type_id"), table_name="wf_budget_items")
    op.drop_column("wf_budget_items", "work_type_id")
    op.add_column(
        "wf_article_mapping", sa.Column("work_type", sa.VARCHAR(length=255), autoincrement=False, nullable=False)
    )
    op.drop_constraint("fk_wf_article_mapping_work_type_id", "wf_article_mapping", type_="foreignkey")
    op.drop_index(op.f("ix_wf_article_mapping_work_type_id"), table_name="wf_article_mapping")
    op.drop_column("wf_article_mapping", "work_type_id")
    # ### end Alembic commands ###
