"""replace contractor_name str with contractor_id fk in wf_mobilization_plans

Revision ID: 73325412b044
Revises: 2ce23d10e027
Create Date: 2026-04-29 12:17:37.930273

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "73325412b044"
down_revision: Union[str, None] = "2ce23d10e027"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("wf_mobilization_plans", sa.Column("contractor_id", sa.UUID(), nullable=False))
    op.create_index(
        op.f("ix_wf_mobilization_plans_contractor_id"), "wf_mobilization_plans", ["contractor_id"], unique=False
    )
    op.create_foreign_key(
        "fk_wf_mobilization_plans_contractor_id", "wf_mobilization_plans", "contractors", ["contractor_id"], ["id"]
    )
    op.drop_column("wf_mobilization_plans", "contractor_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "wf_mobilization_plans",
        sa.Column(
            "contractor_name",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint("fk_wf_mobilization_plans_contractor_id", "wf_mobilization_plans", type_="foreignkey")
    op.drop_index(op.f("ix_wf_mobilization_plans_contractor_id"), table_name="wf_mobilization_plans")
    op.drop_column("wf_mobilization_plans", "contractor_id")
    # ### end Alembic commands ###
