"""Initial schema

Revision ID: 90bb2dc0849e
Revises:
Create Date: 2026-04-22 16:57:54.128697

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "90bb2dc0849e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contractors",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("short_name", sa.String(length=100), nullable=False),
        sa.Column("inn", sa.String(length=20), nullable=True),
        sa.Column("contact_person", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("email", sa.String(length=100), nullable=True),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("raport_id", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_contractors_raport_id"), "contractors", ["raport_id"], unique=True)
    op.create_table(
        "wf_article_mapping",
        sa.Column("article_code", sa.String(length=50), nullable=False),
        sa.Column("article_label", sa.String(length=500), nullable=False),
        sa.Column("work_type", sa.String(length=255), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_wf_article_mapping_article_code"), "wf_article_mapping", ["article_code"], unique=True)
    op.create_table(
        "wf_norms",
        sa.Column("work_type", sa.String(length=255), nullable=False),
        sa.Column("project_class", sa.String(length=50), nullable=False),
        sa.Column("median_day_bdr", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("median_month_bdr", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("q1", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("q3", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("count", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "wf_projects",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("project_class", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("raport_id", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_wf_projects_raport_id"), "wf_projects", ["raport_id"], unique=True)
    op.create_table(
        "work_groups",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("raport_id", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_index(op.f("ix_work_groups_raport_id"), "work_groups", ["raport_id"], unique=True)
    op.create_table(
        "wf_budget_periods",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("period_month", sa.Date(), nullable=False),
        sa.Column("upload_date", sa.DateTime(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["wf_projects.id"], name="fk_wf_budget_periods_project_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_wf_budget_periods_project_id"), "wf_budget_periods", ["project_id"], unique=False)
    op.create_table(
        "wf_project_objects",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("planned_end_date", sa.Date(), nullable=True),
        sa.Column("total_budget_remaining", sa.Numeric(precision=16, scale=2), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("raport_id", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["wf_projects.id"], name="fk_wf_project_objects_project_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_wf_project_objects_project_id"), "wf_project_objects", ["project_id"], unique=False)
    op.create_index(op.f("ix_wf_project_objects_raport_id"), "wf_project_objects", ["raport_id"], unique=True)
    op.create_table(
        "work_types",
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("unit", sa.String(length=20), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("raport_id", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(["group_id"], ["work_groups.id"], name="fk_work_types_group_id"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_index(op.f("ix_work_types_group_id"), "work_types", ["group_id"], unique=False)
    op.create_index(op.f("ix_work_types_raport_id"), "work_types", ["raport_id"], unique=True)
    op.create_table(
        "housings",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("complex_name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("construction_object_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("raport_id", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["construction_object_id"], ["wf_project_objects.id"], name="fk_housings_construction_object_id"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_housings_construction_object_id"), "housings", ["construction_object_id"], unique=False)
    op.create_index(op.f("ix_housings_raport_id"), "housings", ["raport_id"], unique=True)
    op.create_table(
        "wf_budget_items",
        sa.Column("budget_period_id", sa.UUID(), nullable=False),
        sa.Column("object_id", sa.UUID(), nullable=True),
        sa.Column("work_type", sa.String(length=255), nullable=False),
        sa.Column("detailed_article", sa.String(length=500), nullable=True),
        sa.Column("bdr_amount", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("management_completion_amount", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("contractor_id", sa.UUID(), nullable=True),
        sa.Column("remaining_amount", sa.Numeric(precision=16, scale=2), nullable=True),
        sa.Column("planned_end_date", sa.Date(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["budget_period_id"], ["wf_budget_periods.id"], name="fk_wf_budget_items_budget_period_id"
        ),
        sa.ForeignKeyConstraint(["contractor_id"], ["contractors.id"], name="fk_wf_budget_items_contractor_id"),
        sa.ForeignKeyConstraint(["object_id"], ["wf_project_objects.id"], name="fk_wf_budget_items_object_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_wf_budget_items_budget_period_id"), "wf_budget_items", ["budget_period_id"], unique=False)
    op.create_index(op.f("ix_wf_budget_items_contractor_id"), "wf_budget_items", ["contractor_id"], unique=False)
    op.create_index(op.f("ix_wf_budget_items_object_id"), "wf_budget_items", ["object_id"], unique=False)
    op.create_table(
        "wf_challenges",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("object_id", sa.UUID(), nullable=False),
        sa.Column("period_month", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("approved_by", sa.String(length=255), nullable=True),
        sa.Column("approved_at", sa.DateTime(), nullable=True),
        sa.Column("comment", sa.String(length=1000), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["object_id"], ["wf_project_objects.id"], name="fk_wf_challenges_object_id"),
        sa.ForeignKeyConstraint(["project_id"], ["wf_projects.id"], name="fk_wf_challenges_project_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_wf_challenges_object_id"), "wf_challenges", ["object_id"], unique=False)
    op.create_index(op.f("ix_wf_challenges_project_id"), "wf_challenges", ["project_id"], unique=False)
    op.create_table(
        "wf_contractor_assignments",
        sa.Column("contractor_id", sa.UUID(), nullable=False),
        sa.Column("object_id", sa.UUID(), nullable=False),
        sa.Column("work_type", sa.String(length=255), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["contractor_id"], ["contractors.id"], name="fk_wf_contractor_assignments_contractor_id"
        ),
        sa.ForeignKeyConstraint(
            ["object_id"], ["wf_project_objects.id"], name="fk_wf_contractor_assignments_object_id"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_wf_contractor_assignments_contractor_id"), "wf_contractor_assignments", ["contractor_id"], unique=False
    )
    op.create_index(
        op.f("ix_wf_contractor_assignments_object_id"), "wf_contractor_assignments", ["object_id"], unique=False
    )
    op.create_table(
        "wf_headcount_facts",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("object_id", sa.UUID(), nullable=True),
        sa.Column("work_type", sa.String(length=255), nullable=False),
        sa.Column("fact_date", sa.Date(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("contractor_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["contractor_id"], ["contractors.id"], name="fk_wf_headcount_facts_contractor_id"),
        sa.ForeignKeyConstraint(["object_id"], ["wf_project_objects.id"], name="fk_wf_headcount_facts_object_id"),
        sa.ForeignKeyConstraint(["project_id"], ["wf_projects.id"], name="fk_wf_headcount_facts_project_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_wf_headcount_facts_contractor_id"), "wf_headcount_facts", ["contractor_id"], unique=False)
    op.create_index(op.f("ix_wf_headcount_facts_fact_date"), "wf_headcount_facts", ["fact_date"], unique=False)
    op.create_index(op.f("ix_wf_headcount_facts_object_id"), "wf_headcount_facts", ["object_id"], unique=False)
    op.create_index(op.f("ix_wf_headcount_facts_project_id"), "wf_headcount_facts", ["project_id"], unique=False)
    op.create_table(
        "wf_headcount_plans",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("object_id", sa.UUID(), nullable=True),
        sa.Column("work_type", sa.String(length=255), nullable=False),
        sa.Column("period_month", sa.Date(), nullable=False),
        sa.Column("planned_count", sa.Integer(), nullable=False),
        sa.Column("contractor_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["contractor_id"], ["contractors.id"], name="fk_wf_headcount_plans_contractor_id"),
        sa.ForeignKeyConstraint(["object_id"], ["wf_project_objects.id"], name="fk_wf_headcount_plans_object_id"),
        sa.ForeignKeyConstraint(["project_id"], ["wf_projects.id"], name="fk_wf_headcount_plans_project_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_wf_headcount_plans_contractor_id"), "wf_headcount_plans", ["contractor_id"], unique=False)
    op.create_index(op.f("ix_wf_headcount_plans_object_id"), "wf_headcount_plans", ["object_id"], unique=False)
    op.create_index(op.f("ix_wf_headcount_plans_project_id"), "wf_headcount_plans", ["project_id"], unique=False)
    op.create_table(
        "wf_violations",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("object_id", sa.UUID(), nullable=False),
        sa.Column("work_type", sa.String(length=255), nullable=False),
        sa.Column("contractor_id", sa.UUID(), nullable=True),
        sa.Column("violation_date", sa.Date(), nullable=False),
        sa.Column("violation_type", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=False),
        sa.Column("plan_count", sa.Integer(), nullable=False),
        sa.Column("fact_count", sa.Integer(), nullable=False),
        sa.Column("escalated", sa.Boolean(), nullable=False),
        sa.Column("escalated_to", sa.String(length=255), nullable=True),
        sa.Column("resolved", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["contractor_id"], ["contractors.id"], name="fk_wf_violations_contractor_id"),
        sa.ForeignKeyConstraint(["object_id"], ["wf_project_objects.id"], name="fk_wf_violations_object_id"),
        sa.ForeignKeyConstraint(["project_id"], ["wf_projects.id"], name="fk_wf_violations_project_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_wf_violations_contractor_id"), "wf_violations", ["contractor_id"], unique=False)
    op.create_index(op.f("ix_wf_violations_object_id"), "wf_violations", ["object_id"], unique=False)
    op.create_index(op.f("ix_wf_violations_project_id"), "wf_violations", ["project_id"], unique=False)
    op.create_table(
        "alerts",
        sa.Column("alert_type", sa.String(length=10), nullable=False),
        sa.Column("level", sa.String(length=10), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("housing_id", sa.UUID(), nullable=True),
        sa.Column("contractor_id", sa.UUID(), nullable=True),
        sa.Column("rs_user_id", sa.String(length=255), nullable=True),
        sa.Column("recipient_id", sa.String(length=255), nullable=True),
        sa.Column("recipient_role", sa.String(length=20), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("channels_sent", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("sent_at", sa.DateTime(), nullable=True),
        sa.Column("acknowledged", sa.Boolean(), nullable=False),
        sa.Column("acknowledged_at", sa.DateTime(), nullable=True),
        sa.Column("acknowledged_by", sa.String(length=255), nullable=True),
        sa.Column("escalation_level", sa.Integer(), nullable=False),
        sa.Column("escalated_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["contractor_id"], ["contractors.id"], name="fk_alerts_contractor_id"),
        sa.ForeignKeyConstraint(["housing_id"], ["housings.id"], name="fk_alerts_housing_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_alerts_alert_type"), "alerts", ["alert_type"], unique=False)
    op.create_index(op.f("ix_alerts_contractor_id"), "alerts", ["contractor_id"], unique=False)
    op.create_index(op.f("ix_alerts_date"), "alerts", ["date"], unique=False)
    op.create_index(op.f("ix_alerts_housing_id"), "alerts", ["housing_id"], unique=False)
    op.create_index(op.f("ix_alerts_level"), "alerts", ["level"], unique=False)
    op.create_table(
        "daily_summaries",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("housing_id", sa.UUID(), nullable=False),
        sa.Column("total_planned", sa.Integer(), nullable=False),
        sa.Column("total_done_full", sa.Integer(), nullable=False),
        sa.Column("total_done_partial", sa.Integer(), nullable=False),
        sa.Column("total_done_over", sa.Integer(), nullable=False),
        sa.Column("total_not_done", sa.Integer(), nullable=False),
        sa.Column("total_no_report", sa.Integer(), nullable=False),
        sa.Column("total_unplanned", sa.Integer(), nullable=False),
        sa.Column("completion_rate", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("weighted_completion", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("submission_rate", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("contractor_details", sa.JSON(), nullable=True),
        sa.Column("alerts", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["housing_id"], ["housings.id"], name="fk_daily_summaries_housing_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_daily_summaries_date"), "daily_summaries", ["date"], unique=False)
    op.create_index(op.f("ix_daily_summaries_housing_id"), "daily_summaries", ["housing_id"], unique=False)
    op.create_table(
        "sections",
        sa.Column("housing_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("section_number", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("raport_id", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(["housing_id"], ["housings.id"], name="fk_sections_housing_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sections_housing_id"), "sections", ["housing_id"], unique=False)
    op.create_index(op.f("ix_sections_raport_id"), "sections", ["raport_id"], unique=True)
    op.create_table(
        "tech_sequence_items",
        sa.Column("housing_id", sa.UUID(), nullable=False),
        sa.Column("work_type_id", sa.UUID(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("depends_on", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("dependency_type", sa.String(length=20), nullable=False),
        sa.Column("lag_days", sa.Integer(), nullable=False),
        sa.Column("estimated_days", sa.Integer(), nullable=False),
        sa.Column("daily_norm_volume", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("total_volume", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["housing_id"], ["housings.id"], name="fk_tech_sequence_items_housing_id"),
        sa.ForeignKeyConstraint(["work_type_id"], ["work_types.id"], name="fk_tech_sequence_items_work_type_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tech_sequence_items_housing_id"), "tech_sequence_items", ["housing_id"], unique=False)
    op.create_index(op.f("ix_tech_sequence_items_work_type_id"), "tech_sequence_items", ["work_type_id"], unique=False)
    op.create_table(
        "wf_challenge_items",
        sa.Column("challenge_id", sa.UUID(), nullable=False),
        sa.Column("work_type", sa.String(length=255), nullable=False),
        sa.Column("system_baseline", sa.Integer(), nullable=False),
        sa.Column("requested_count", sa.Integer(), nullable=False),
        sa.Column("approved_count", sa.Integer(), nullable=True),
        sa.Column("requires_mobilization_plan", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["challenge_id"], ["wf_challenges.id"], name="fk_wf_challenge_items_challenge_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_wf_challenge_items_challenge_id"), "wf_challenge_items", ["challenge_id"], unique=False)
    op.create_table(
        "contractor_assignments",
        sa.Column("contractor_id", sa.UUID(), nullable=False),
        sa.Column("housing_id", sa.UUID(), nullable=False),
        sa.Column("section_id", sa.UUID(), nullable=True),
        sa.Column("work_group_id", sa.UUID(), nullable=True),
        sa.Column("work_type_ids", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["contractor_id"], ["contractors.id"], name="fk_contractor_assignments_contractor_id"),
        sa.ForeignKeyConstraint(["housing_id"], ["housings.id"], name="fk_contractor_assignments_housing_id"),
        sa.ForeignKeyConstraint(["section_id"], ["sections.id"], name="fk_contractor_assignments_section_id"),
        sa.ForeignKeyConstraint(["work_group_id"], ["work_groups.id"], name="fk_contractor_assignments_work_group_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_contractor_assignments_contractor_id"), "contractor_assignments", ["contractor_id"], unique=False
    )
    op.create_index(
        op.f("ix_contractor_assignments_housing_id"), "contractor_assignments", ["housing_id"], unique=False
    )
    op.create_index(
        op.f("ix_contractor_assignments_section_id"), "contractor_assignments", ["section_id"], unique=False
    )
    op.create_index(
        op.f("ix_contractor_assignments_work_group_id"), "contractor_assignments", ["work_group_id"], unique=False
    )
    op.create_table(
        "floors",
        sa.Column("section_id", sa.UUID(), nullable=False),
        sa.Column("floor_number", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("raport_id", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(["section_id"], ["sections.id"], name="fk_floors_section_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_floors_raport_id"), "floors", ["raport_id"], unique=True)
    op.create_index(op.f("ix_floors_section_id"), "floors", ["section_id"], unique=False)
    op.create_table(
        "wf_mobilization_plans",
        sa.Column("challenge_item_id", sa.UUID(), nullable=False),
        sa.Column("planned_date", sa.Date(), nullable=False),
        sa.Column("action", sa.String(length=500), nullable=False),
        sa.Column("headcount_delta", sa.Integer(), nullable=False),
        sa.Column("contractor_name", sa.String(length=255), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["challenge_item_id"], ["wf_challenge_items.id"], name="fk_wf_mobilization_plans_challenge_item_id"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_wf_mobilization_plans_challenge_item_id"),
        "wf_mobilization_plans",
        ["challenge_item_id"],
        unique=False,
    )
    op.create_table(
        "plan_items",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("housing_id", sa.UUID(), nullable=False),
        sa.Column("section_id", sa.UUID(), nullable=False),
        sa.Column("floor_id", sa.UUID(), nullable=False),
        sa.Column("work_type_id", sa.UUID(), nullable=False),
        sa.Column("contractor_id", sa.UUID(), nullable=False),
        sa.Column("planned_volume", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("unit", sa.String(length=20), nullable=False),
        sa.Column("rs_confirmed", sa.Boolean(), nullable=False),
        sa.Column("rs_confirmed_at", sa.DateTime(), nullable=True),
        sa.Column("rs_confirmed_by", sa.String(length=255), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["contractor_id"], ["contractors.id"], name="fk_plan_items_contractor_id"),
        sa.ForeignKeyConstraint(["floor_id"], ["floors.id"], name="fk_plan_items_floor_id"),
        sa.ForeignKeyConstraint(["housing_id"], ["housings.id"], name="fk_plan_items_housing_id"),
        sa.ForeignKeyConstraint(["section_id"], ["sections.id"], name="fk_plan_items_section_id"),
        sa.ForeignKeyConstraint(["work_type_id"], ["work_types.id"], name="fk_plan_items_work_type_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_plan_items_contractor_id"), "plan_items", ["contractor_id"], unique=False)
    op.create_index(op.f("ix_plan_items_date"), "plan_items", ["date"], unique=False)
    op.create_index(op.f("ix_plan_items_floor_id"), "plan_items", ["floor_id"], unique=False)
    op.create_index(op.f("ix_plan_items_housing_id"), "plan_items", ["housing_id"], unique=False)
    op.create_index(op.f("ix_plan_items_section_id"), "plan_items", ["section_id"], unique=False)
    op.create_index(op.f("ix_plan_items_work_type_id"), "plan_items", ["work_type_id"], unique=False)
    op.create_table(
        "wf_mobilization_checkpoints",
        sa.Column("mobilization_plan_id", sa.UUID(), nullable=False),
        sa.Column("check_date", sa.Date(), nullable=False),
        sa.Column("expected_cumulative", sa.Integer(), nullable=False),
        sa.Column("actual_cumulative", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("violation_recorded", sa.Boolean(), nullable=False),
        sa.Column("violation_comment", sa.String(length=1000), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["mobilization_plan_id"],
            ["wf_mobilization_plans.id"],
            name="fk_wf_mobilization_checkpoints_plan_id",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_wf_mobilization_checkpoints_mobilization_plan_id"),
        "wf_mobilization_checkpoints",
        ["mobilization_plan_id"],
        unique=False,
    )
    op.create_table(
        "work_facts",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("housing_id", sa.UUID(), nullable=False),
        sa.Column("section_id", sa.UUID(), nullable=False),
        sa.Column("floor_id", sa.UUID(), nullable=False),
        sa.Column("work_type_id", sa.UUID(), nullable=False),
        sa.Column("contractor_id", sa.UUID(), nullable=False),
        sa.Column("actual_volume", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("unit", sa.String(length=20), nullable=False),
        sa.Column("submitted_at", sa.DateTime(), nullable=False),
        sa.Column("submitted_by", sa.String(length=255), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("photo_urls", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["contractor_id"], ["contractors.id"], name="fk_work_facts_contractor_id"),
        sa.ForeignKeyConstraint(["floor_id"], ["floors.id"], name="fk_work_facts_floor_id"),
        sa.ForeignKeyConstraint(["housing_id"], ["housings.id"], name="fk_work_facts_housing_id"),
        sa.ForeignKeyConstraint(["section_id"], ["sections.id"], name="fk_work_facts_section_id"),
        sa.ForeignKeyConstraint(["work_type_id"], ["work_types.id"], name="fk_work_facts_work_type_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_work_facts_contractor_id"), "work_facts", ["contractor_id"], unique=False)
    op.create_index(op.f("ix_work_facts_date"), "work_facts", ["date"], unique=False)
    op.create_index(op.f("ix_work_facts_floor_id"), "work_facts", ["floor_id"], unique=False)
    op.create_index(op.f("ix_work_facts_housing_id"), "work_facts", ["housing_id"], unique=False)
    op.create_index(op.f("ix_work_facts_section_id"), "work_facts", ["section_id"], unique=False)
    op.create_index(op.f("ix_work_facts_work_type_id"), "work_facts", ["work_type_id"], unique=False)
    op.create_table(
        "plan_adjustments",
        sa.Column("plan_item_id", sa.UUID(), nullable=False),
        sa.Column("original_field", sa.String(length=50), nullable=False),
        sa.Column("original_value", sa.String(length=255), nullable=False),
        sa.Column("new_value", sa.String(length=255), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("adjusted_by", sa.String(length=255), nullable=False),
        sa.Column("adjusted_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["plan_item_id"], ["plan_items.id"], name="fk_plan_adjustments_plan_item_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_plan_adjustments_plan_item_id"), "plan_adjustments", ["plan_item_id"], unique=False)
    op.create_table(
        "reconciliation_results",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("housing_id", sa.UUID(), nullable=False),
        sa.Column("section_id", sa.UUID(), nullable=False),
        sa.Column("floor_id", sa.UUID(), nullable=False),
        sa.Column("work_type_id", sa.UUID(), nullable=False),
        sa.Column("contractor_id", sa.UUID(), nullable=False),
        sa.Column("planned_volume", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("actual_volume", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("completion_ratio", sa.Numeric(precision=8, scale=4), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("pattern", sa.String(length=30), nullable=True),
        sa.Column("plan_item_id", sa.UUID(), nullable=True),
        sa.Column("work_fact_id", sa.UUID(), nullable=True),
        sa.Column("fact_submitted_at", sa.DateTime(), nullable=True),
        sa.Column("fact_is_late", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["contractor_id"], ["contractors.id"], name="fk_reconciliation_results_contractor_id"),
        sa.ForeignKeyConstraint(["floor_id"], ["floors.id"], name="fk_reconciliation_results_floor_id"),
        sa.ForeignKeyConstraint(["housing_id"], ["housings.id"], name="fk_reconciliation_results_housing_id"),
        sa.ForeignKeyConstraint(["plan_item_id"], ["plan_items.id"], name="fk_reconciliation_results_plan_item_id"),
        sa.ForeignKeyConstraint(["section_id"], ["sections.id"], name="fk_reconciliation_results_section_id"),
        sa.ForeignKeyConstraint(["work_fact_id"], ["work_facts.id"], name="fk_reconciliation_results_work_fact_id"),
        sa.ForeignKeyConstraint(["work_type_id"], ["work_types.id"], name="fk_reconciliation_results_work_type_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reconciliation_results_contractor_id"), "reconciliation_results", ["contractor_id"], unique=False
    )
    op.create_index(op.f("ix_reconciliation_results_date"), "reconciliation_results", ["date"], unique=False)
    op.create_index(op.f("ix_reconciliation_results_floor_id"), "reconciliation_results", ["floor_id"], unique=False)
    op.create_index(
        op.f("ix_reconciliation_results_housing_id"), "reconciliation_results", ["housing_id"], unique=False
    )
    op.create_index(
        op.f("ix_reconciliation_results_plan_item_id"), "reconciliation_results", ["plan_item_id"], unique=False
    )
    op.create_index(
        op.f("ix_reconciliation_results_section_id"), "reconciliation_results", ["section_id"], unique=False
    )
    op.create_index(
        op.f("ix_reconciliation_results_work_fact_id"), "reconciliation_results", ["work_fact_id"], unique=False
    )
    op.create_index(
        op.f("ix_reconciliation_results_work_type_id"), "reconciliation_results", ["work_type_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reconciliation_results_work_type_id"), table_name="reconciliation_results")
    op.drop_index(op.f("ix_reconciliation_results_work_fact_id"), table_name="reconciliation_results")
    op.drop_index(op.f("ix_reconciliation_results_section_id"), table_name="reconciliation_results")
    op.drop_index(op.f("ix_reconciliation_results_plan_item_id"), table_name="reconciliation_results")
    op.drop_index(op.f("ix_reconciliation_results_housing_id"), table_name="reconciliation_results")
    op.drop_index(op.f("ix_reconciliation_results_floor_id"), table_name="reconciliation_results")
    op.drop_index(op.f("ix_reconciliation_results_date"), table_name="reconciliation_results")
    op.drop_index(op.f("ix_reconciliation_results_contractor_id"), table_name="reconciliation_results")
    op.drop_table("reconciliation_results")
    op.drop_index(op.f("ix_plan_adjustments_plan_item_id"), table_name="plan_adjustments")
    op.drop_table("plan_adjustments")
    op.drop_index(op.f("ix_work_facts_work_type_id"), table_name="work_facts")
    op.drop_index(op.f("ix_work_facts_section_id"), table_name="work_facts")
    op.drop_index(op.f("ix_work_facts_housing_id"), table_name="work_facts")
    op.drop_index(op.f("ix_work_facts_floor_id"), table_name="work_facts")
    op.drop_index(op.f("ix_work_facts_date"), table_name="work_facts")
    op.drop_index(op.f("ix_work_facts_contractor_id"), table_name="work_facts")
    op.drop_table("work_facts")
    op.drop_index(op.f("ix_wf_mobilization_checkpoints_mobilization_plan_id"), table_name="wf_mobilization_checkpoints")
    op.drop_table("wf_mobilization_checkpoints")
    op.drop_index(op.f("ix_plan_items_work_type_id"), table_name="plan_items")
    op.drop_index(op.f("ix_plan_items_section_id"), table_name="plan_items")
    op.drop_index(op.f("ix_plan_items_housing_id"), table_name="plan_items")
    op.drop_index(op.f("ix_plan_items_floor_id"), table_name="plan_items")
    op.drop_index(op.f("ix_plan_items_date"), table_name="plan_items")
    op.drop_index(op.f("ix_plan_items_contractor_id"), table_name="plan_items")
    op.drop_table("plan_items")
    op.drop_index(op.f("ix_wf_mobilization_plans_challenge_item_id"), table_name="wf_mobilization_plans")
    op.drop_table("wf_mobilization_plans")
    op.drop_index(op.f("ix_floors_section_id"), table_name="floors")
    op.drop_index(op.f("ix_floors_raport_id"), table_name="floors")
    op.drop_table("floors")
    op.drop_index(op.f("ix_contractor_assignments_work_group_id"), table_name="contractor_assignments")
    op.drop_index(op.f("ix_contractor_assignments_section_id"), table_name="contractor_assignments")
    op.drop_index(op.f("ix_contractor_assignments_housing_id"), table_name="contractor_assignments")
    op.drop_index(op.f("ix_contractor_assignments_contractor_id"), table_name="contractor_assignments")
    op.drop_table("contractor_assignments")
    op.drop_index(op.f("ix_wf_challenge_items_challenge_id"), table_name="wf_challenge_items")
    op.drop_table("wf_challenge_items")
    op.drop_index(op.f("ix_tech_sequence_items_work_type_id"), table_name="tech_sequence_items")
    op.drop_index(op.f("ix_tech_sequence_items_housing_id"), table_name="tech_sequence_items")
    op.drop_table("tech_sequence_items")
    op.drop_index(op.f("ix_sections_raport_id"), table_name="sections")
    op.drop_index(op.f("ix_sections_housing_id"), table_name="sections")
    op.drop_table("sections")
    op.drop_index(op.f("ix_daily_summaries_housing_id"), table_name="daily_summaries")
    op.drop_index(op.f("ix_daily_summaries_date"), table_name="daily_summaries")
    op.drop_table("daily_summaries")
    op.drop_index(op.f("ix_alerts_level"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_housing_id"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_date"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_contractor_id"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_alert_type"), table_name="alerts")
    op.drop_table("alerts")
    op.drop_index(op.f("ix_wf_violations_project_id"), table_name="wf_violations")
    op.drop_index(op.f("ix_wf_violations_object_id"), table_name="wf_violations")
    op.drop_index(op.f("ix_wf_violations_contractor_id"), table_name="wf_violations")
    op.drop_table("wf_violations")
    op.drop_index(op.f("ix_wf_headcount_plans_project_id"), table_name="wf_headcount_plans")
    op.drop_index(op.f("ix_wf_headcount_plans_object_id"), table_name="wf_headcount_plans")
    op.drop_index(op.f("ix_wf_headcount_plans_contractor_id"), table_name="wf_headcount_plans")
    op.drop_table("wf_headcount_plans")
    op.drop_index(op.f("ix_wf_headcount_facts_project_id"), table_name="wf_headcount_facts")
    op.drop_index(op.f("ix_wf_headcount_facts_object_id"), table_name="wf_headcount_facts")
    op.drop_index(op.f("ix_wf_headcount_facts_fact_date"), table_name="wf_headcount_facts")
    op.drop_index(op.f("ix_wf_headcount_facts_contractor_id"), table_name="wf_headcount_facts")
    op.drop_table("wf_headcount_facts")
    op.drop_index(op.f("ix_wf_contractor_assignments_object_id"), table_name="wf_contractor_assignments")
    op.drop_index(op.f("ix_wf_contractor_assignments_contractor_id"), table_name="wf_contractor_assignments")
    op.drop_table("wf_contractor_assignments")
    op.drop_index(op.f("ix_wf_challenges_project_id"), table_name="wf_challenges")
    op.drop_index(op.f("ix_wf_challenges_object_id"), table_name="wf_challenges")
    op.drop_table("wf_challenges")
    op.drop_index(op.f("ix_wf_budget_items_object_id"), table_name="wf_budget_items")
    op.drop_index(op.f("ix_wf_budget_items_contractor_id"), table_name="wf_budget_items")
    op.drop_index(op.f("ix_wf_budget_items_budget_period_id"), table_name="wf_budget_items")
    op.drop_table("wf_budget_items")
    op.drop_index(op.f("ix_housings_raport_id"), table_name="housings")
    op.drop_index(op.f("ix_housings_construction_object_id"), table_name="housings")
    op.drop_table("housings")
    op.drop_index(op.f("ix_work_types_raport_id"), table_name="work_types")
    op.drop_index(op.f("ix_work_types_group_id"), table_name="work_types")
    op.drop_table("work_types")
    op.drop_index(op.f("ix_wf_project_objects_raport_id"), table_name="wf_project_objects")
    op.drop_index(op.f("ix_wf_project_objects_project_id"), table_name="wf_project_objects")
    op.drop_table("wf_project_objects")
    op.drop_index(op.f("ix_wf_budget_periods_project_id"), table_name="wf_budget_periods")
    op.drop_table("wf_budget_periods")
    op.drop_index(op.f("ix_work_groups_raport_id"), table_name="work_groups")
    op.drop_table("work_groups")
    op.drop_index(op.f("ix_wf_projects_raport_id"), table_name="wf_projects")
    op.drop_table("wf_projects")
    op.drop_table("wf_norms")
    op.drop_index(op.f("ix_wf_article_mapping_article_code"), table_name="wf_article_mapping")
    op.drop_table("wf_article_mapping")
    op.drop_index(op.f("ix_contractors_raport_id"), table_name="contractors")
    op.drop_table("contractors")
    # ### end Alembic commands ###
